#ifndef __DT_BINDING_PINCTRL_BFLB__
#define __DT_BINDING_PINCTRL_BFLB__

/* pinmux functions */
#define BFLB_PINMUX_FUNC_SDH		0
#define BFLB_PINMUX_FUNC_SPI0		1
#define BFLB_PINMUX_FUNC_QSPI_FLASH	2
#define BFLB_PINMUX_FUNC_I2S		3
#define BFLB_PINMUX_FUNC_PDM		4
#define BFLB_PINMUX_FUNC_I2C0		5
#define BFLB_PINMUX_FUNC_I2C1		6
#define BFLB_PINMUX_FUNC_UART		7
#define BFLB_PINMUX_FUNC_EMAC		8
#define BFLB_PINMUX_FUNC_CAM		9
#define BFLB_PINMUX_FUNC_ANALOG		10
#define BFLB_PINMUX_FUNC_GPIO		11
#define BFLB_PINMUX_FUNC_RF_ADDA	12
#define BFLB_PINMUX_FUNC_SCAN_TEST	13
#define BFLB_PINMUX_FUNC_AUDIO_TEST	14
#define BFLB_PINMUX_FUNC_DEBUG		15
#define BFLB_PINMUX_FUNC_PWM0		16
#define BFLB_PINMUX_FUNC_PWM1		17
#define BFLB_PINMUX_FUNC_MM_SPI		18
#define BFLB_PINMUX_FUNC_MM_I2C0	19
#define BFLB_PINMUX_FUNC_MM_I2C1	20
#define BFLB_PINMUX_FUNC_MM_UART	21
#define BFLB_PINMUX_FUNC_DBI_B		22
#define BFLB_PINMUX_FUNC_DBI_C		23
#define BFLB_PINMUX_FUNC_DPI		24
#define BFLB_PINMUX_FUNC_JTAG_LP	25
#define BFLB_PINMUX_FUNC_JTAG_M0	26
#define BFLB_PINMUX_FUNC_JTAG_D0	27
#define BFLB_PINMUX_FUNC_RF_EXT_PA	28
#define BFLB_PINMUX_FUNC_ANT_SW		29
#define BFLB_PINMUX_FUNC_USB_TEST	30
#define BFLB_PINMUX_FUNC_CLOCK		31
#define BFLB_PINMUX_FUNC_NONE   	32

/* __DT_BINDING_PINCTRL_BFLB__ */
#endif
